#ifndef PLATFORM_GPIO_CONFIG_HW1_H
#define PLATFORM_GPIO_CONFIG_HW1_H

#include <driver/gpio.h>
#include <esp_adc/adc_continuous.h>

#define IMU_INT_GPIO GPIO_NUM_35

#define UART1_TX_GPIO GPIO_NUM_1
#define UART1_RX_GPIO GPIO_NUM_3

#define I2C1_SDA_GPIO GPIO_NUM_21
#define I2C1_SCL_GPIO GPIO_NUM_22

#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_0

#define MOTOR1_GPIO GPIO_NUM_25
#define MOTOR2_GPIO GPIO_NUM_26
#define MOTOR3_GPIO GPIO_NUM_27
#define MOTOR4_GPIO GPIO_NUM_14

#define RC_TX_GPIO GPIO_NUM_0
#define RC_RX_GPIO GPIO_NUM_34

#endif