idf_component_register(SRCS "main.c"
	"platform/bus/bus_tree.c" "platform/bus/spi.c" "platform/bus/uart.c" "platform/bus/i2c.c"
	"platform/misc/util.c" "platform/misc/config.c"
	"platform/drivers/wifi.c" "platform/drivers/anotc_wifi.c"
	"platform/clocksource/default_source.c" "platform/clocksource/imu_source.c"
	"platform/esc/dshot.c"
	"platform/mixer/mixer.c" "platform/mixer/dshot.c"
	"bus/bus.c" "bus/spi_dev.c" "bus/i2c_dev.c"
	"drivers/imu/icm20948.c" "drivers/imu/mpu6050.c" "drivers/imu/mpu6500.c"
	"drivers/barometer/bmp280.c"
	"drivers/compass/lis3mdl.c"
	"drivers/anotc_uart.c"
	"sensors/imu.c" "sensors/barometer.c"
	"esc/dshot.c"
	"mixer/mixer.c" "mixer/dshot.c"
	"flight/flight.c" "flight/attitude.c" "flight/altitude.c"
	"attitude/MahonyAHRS.c"
	"clocksource/clocksource.c"
	"anotc/anotc.c" "anotc/anotc_other_frame.c" "anotc/anotc_rec_frame.c" "anotc/anotc_decode.c" "anotc/anotc_flight_frame.c" "anotc/anotc_control_frame.c" "anotc/anotc_rec_cmd_frame.c" "anotc/anotc_config_frame.c" "anotc/anotc_custom_config.c" "anotc/anotc_custom_cmd.c" "anotc/anotc_custom_frame.c"
	"misc/iir_filter.c" "misc/config.c"
	"task/flight_log_task.c" "task/wifi.c"
	REQUIRES "driver" "esp_timer" "esp_wifi" "nvs_flash" "log"
                    INCLUDE_DIRS ".")
