idf_component_register(SRCS "main.c"
	"bus/bus.c" "bus/spi_dev.c" "bus/uart_dev.c" "bus/i2c_dev.c"
	"drivers/bus/bus_tree.c" "drivers/bus/spi.c" "drivers/bus/uart.c" "drivers/bus/i2c.c"
	"drivers/imu/icm20948.c" "drivers/imu/mpu6050.c"
	"drivers/barometer/bmp280.c"
	"sensors/imu.c"
	"flight/flight.c"
	"misc/util.c" 
	"clocksource/clocksource.c" "clocksource/default_source.c"
	REQUIRES "driver" "esp_timer" "esp_wifi"
                    INCLUDE_DIRS ".")
