#ifndef DRIVERS_MAGNETOMETER_LIS3MDL_H
#define DRIVERS_MAGNETOMETER_LIS3MDL_H

#include "bus/bus.h"

#define LIS3MDL_WHOAMI_VALUE 0x3D

#define LIS3MDL_RESOLUTION_4 6842.0f

#define LIS3MDL_REG_OFFSET_X_REG_L_M 0x5
#define LIS3MDL_REG_OFFSET_X_REG_H_M 0x6
#define LIS3MDL_REG_OFFSET_Y_REG_L_M 0x7
#define LIS3MDL_REG_OFFSET_Y_REG_H_M 0x8
#define LIS3MDL_REG_OFFSET_Z_REG_L_M 0x9
#define LIS3MDL_REG_OFFSET_Z_REG_H_M 0xA
#define LIS3MDL_REG_WHO_AM_I 0xF
#define LIS3MDL_REG_CTRL_REG1 0x20
#define LIS3MDL_REG_CTRL_REG2 0x21
#define LIS3MDL_REG_CTRL_REG3 0x22
#define LIS3MDL_REG_CTRL_REG4 0x23
#define LIS3MDL_REG_CTRL_REG5 0x24
#define LIS3MDL_REG_STATUS_REG 0x27
#define LIS3MDL_REG_OUT_X_L 0x28
#define LIS3MDL_REG_OUT_X_H 0x29
#define LIS3MDL_REG_OUT_Y_L 0x2A
#define LIS3MDL_REG_OUT_Y_H 0x2B
#define LIS3MDL_REG_OUT_Z_L 0x2C
#define LIS3MDL_REG_OUT_Z_H 0x2D
#define LIS3MDL_REG_TEMP_OUT_L 0x2E
#define LIS3MDL_REG_TEMP_OUT_H 0x2F
#define LIS3MDL_REG_INT_CFG 0x30
#define LIS3MDL_REG_INT_SRC 0x31
#define LIS3MDL_REG_INT_THS_L 0x32
#define LIS3MDL_REG_INT_THS_H 0x33

int lis3mdl_prob(struct bus_dev *dev);
#endif